server:
  port: 8080
  servlet:
    context-path: /ShopmeAdmin
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/shopmedb
    username: root
    password: hclee
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
